language: rust
branches:
  only:
  - master
matrix:
  include:
    - name: "nightly"
      rust: nightly
      before_script:
        - rustup target add wasm32-unknown-unknown
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
        - source ~/.nvm/nvm.sh
        - nvm install node
      script:
        - make
